-- =============================================================================
-- One-time Snowflake platform setup (run by an admin: SYSADMIN + SECURITYADMIN).
-- Creates compute with cost guardrails, layered schemas, least-privilege roles,
-- a key-pair service user, PII masking and the Azure Data Lake stage.
-- Idempotent: safe to re-run.
-- =============================================================================

USE ROLE SYSADMIN;

-- ---------- Compute ------------------------------------------------------------
CREATE WAREHOUSE IF NOT EXISTS REVINTEL_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    STATEMENT_TIMEOUT_IN_SECONDS = 3600
    COMMENT = 'Customer & Revenue Intelligence: ELT + BI';

-- ---------- Database and layers ---------------------------------------------------
CREATE DATABASE IF NOT EXISTS REVINTEL DATA_RETENTION_TIME_IN_DAYS = 7;
CREATE SCHEMA IF NOT EXISTS REVINTEL.RAW       COMMENT = 'Append-only batches from the Python ingest stage';
CREATE SCHEMA IF NOT EXISTS REVINTEL.STAGING   COMMENT = 'dbt staging views (deduplicated, typed)';
CREATE SCHEMA IF NOT EXISTS REVINTEL.SNAPSHOTS COMMENT = 'dbt SCD Type 2 snapshots';
CREATE SCHEMA IF NOT EXISTS REVINTEL.CORE      COMMENT = 'Star schema: dimensions and facts';
CREATE SCHEMA IF NOT EXISTS REVINTEL.ANALYTICS COMMENT = 'Business metrics consumed by Power BI';
CREATE SCHEMA IF NOT EXISTS REVINTEL.OPS       COMMENT = 'Pipeline audit log, data-quality results, policies';

-- ---------- Cost guardrail ---------------------------------------------------------
USE ROLE ACCOUNTADMIN;
CREATE RESOURCE MONITOR IF NOT EXISTS REVINTEL_MONTHLY
    WITH CREDIT_QUOTA = 50 FREQUENCY = MONTHLY START_TIMESTAMP = IMMEDIATELY
    TRIGGERS ON 75 PERCENT DO NOTIFY
             ON 100 PERCENT DO SUSPEND
             ON 110 PERCENT DO SUSPEND_IMMEDIATE;
ALTER WAREHOUSE REVINTEL_WH SET RESOURCE_MONITOR = REVINTEL_MONTHLY;

-- ---------- Roles (least privilege) ---------------------------------------------------
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS REVINTEL_LOADER      COMMENT = 'Python ingest: writes RAW and OPS';
CREATE ROLE IF NOT EXISTS REVINTEL_TRANSFORMER COMMENT = 'dbt: reads RAW, owns STAGING/SNAPSHOTS/CORE/ANALYTICS';
CREATE ROLE IF NOT EXISTS REVINTEL_REPORTER    COMMENT = 'Power BI / analysts: read CORE and ANALYTICS';
GRANT ROLE REVINTEL_LOADER, REVINTEL_TRANSFORMER, REVINTEL_REPORTER TO ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE REVINTEL_WH TO ROLE REVINTEL_LOADER;
GRANT USAGE ON WAREHOUSE REVINTEL_WH TO ROLE REVINTEL_TRANSFORMER;
GRANT USAGE ON WAREHOUSE REVINTEL_WH TO ROLE REVINTEL_REPORTER;
GRANT USAGE ON DATABASE REVINTEL TO ROLE REVINTEL_LOADER;
GRANT USAGE ON DATABASE REVINTEL TO ROLE REVINTEL_TRANSFORMER;
GRANT USAGE ON DATABASE REVINTEL TO ROLE REVINTEL_REPORTER;
GRANT CREATE SCHEMA ON DATABASE REVINTEL TO ROLE REVINTEL_TRANSFORMER;  -- dev_<user>_* sandboxes

-- Loader
GRANT ALL ON SCHEMA REVINTEL.RAW TO ROLE REVINTEL_LOADER;
GRANT ALL ON SCHEMA REVINTEL.OPS TO ROLE REVINTEL_LOADER;
GRANT ALL ON FUTURE TABLES IN SCHEMA REVINTEL.RAW TO ROLE REVINTEL_LOADER;
GRANT ALL ON FUTURE TABLES IN SCHEMA REVINTEL.OPS TO ROLE REVINTEL_LOADER;

-- Transformer
GRANT USAGE ON SCHEMA REVINTEL.RAW TO ROLE REVINTEL_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA REVINTEL.RAW TO ROLE REVINTEL_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA REVINTEL.RAW TO ROLE REVINTEL_TRANSFORMER;
GRANT ALL ON SCHEMA REVINTEL.STAGING TO ROLE REVINTEL_TRANSFORMER;
GRANT ALL ON SCHEMA REVINTEL.SNAPSHOTS TO ROLE REVINTEL_TRANSFORMER;
GRANT ALL ON SCHEMA REVINTEL.CORE TO ROLE REVINTEL_TRANSFORMER;
GRANT ALL ON SCHEMA REVINTEL.ANALYTICS TO ROLE REVINTEL_TRANSFORMER;
GRANT USAGE ON SCHEMA REVINTEL.OPS TO ROLE REVINTEL_TRANSFORMER;

-- Reporter (Power BI)
GRANT USAGE ON SCHEMA REVINTEL.CORE TO ROLE REVINTEL_REPORTER;
GRANT USAGE ON SCHEMA REVINTEL.ANALYTICS TO ROLE REVINTEL_REPORTER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA REVINTEL.CORE TO ROLE REVINTEL_REPORTER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA REVINTEL.ANALYTICS TO ROLE REVINTEL_REPORTER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA REVINTEL.ANALYTICS TO ROLE REVINTEL_REPORTER;

-- ---------- Service user: RSA key-pair auth, no password ------------------------
-- Generate the key pair (store the private key in Azure Key Vault as 'snowflake-private-key'):
--   openssl genrsa 2048 | openssl pkcs8 -topk8 -inform PEM -out rsa_key.p8 -nocrypt
--   openssl rsa -in rsa_key.p8 -pubout -out rsa_key.pub
CREATE USER IF NOT EXISTS SVC_REVINTEL
    TYPE = SERVICE
    DEFAULT_ROLE = REVINTEL_TRANSFORMER
    DEFAULT_WAREHOUSE = REVINTEL_WH
    RSA_PUBLIC_KEY = '<contents of rsa_key.pub without header/footer>'
    COMMENT = 'Airflow / Container Apps pipeline';
GRANT ROLE REVINTEL_LOADER TO USER SVC_REVINTEL;
GRANT ROLE REVINTEL_TRANSFORMER TO USER SVC_REVINTEL;

-- ---------- PII: dynamic data masking ----------------------------------------
-- Applied to CORE.DIM_CUSTOMER.EMAIL by a dbt post-hook (macros/mask_pii.sql).
USE ROLE SYSADMIN;
CREATE MASKING POLICY IF NOT EXISTS REVINTEL.OPS.PII_EMAIL_MASK AS (val STRING) RETURNS STRING ->
    CASE
        WHEN IS_ROLE_IN_SESSION('REVINTEL_TRANSFORMER') THEN val
        ELSE REGEXP_REPLACE(val, '^[^@]+', '*****')
    END;
USE ROLE SECURITYADMIN;
GRANT APPLY ON MASKING POLICY REVINTEL.OPS.PII_EMAIL_MASK TO ROLE REVINTEL_TRANSFORMER;

-- ---------- Azure Data Lake integration --------------------------------------------
-- Replace <tenant-id> and <storage-account> with the Bicep outputs. Then run
--   DESC STORAGE INTEGRATION REVINTEL_AZURE_INT;
-- open AZURE_CONSENT_URL and grant the AZURE_MULTI_TENANT_APP_NAME service
-- principal "Storage Blob Data Reader" on the storage account.
USE ROLE ACCOUNTADMIN;
CREATE STORAGE INTEGRATION IF NOT EXISTS REVINTEL_AZURE_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'AZURE'
    ENABLED = TRUE
    AZURE_TENANT_ID = '<tenant-id>'
    STORAGE_ALLOWED_LOCATIONS = ('azure://<storage-account>.blob.core.windows.net/revintel/clean/');
GRANT USAGE ON INTEGRATION REVINTEL_AZURE_INT TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
CREATE FILE FORMAT IF NOT EXISTS REVINTEL.RAW.PARQUET_FMT TYPE = PARQUET USE_LOGICAL_TYPE = TRUE;

CREATE STAGE IF NOT EXISTS REVINTEL.RAW.AZURE_CLEAN_STAGE
    URL = 'azure://<storage-account>.blob.core.windows.net/revintel/clean/'
    STORAGE_INTEGRATION = REVINTEL_AZURE_INT
    FILE_FORMAT = REVINTEL.RAW.PARQUET_FMT;
GRANT USAGE ON FILE FORMAT REVINTEL.RAW.PARQUET_FMT TO ROLE REVINTEL_LOADER;
GRANT USAGE ON STAGE REVINTEL.RAW.AZURE_CLEAN_STAGE TO ROLE REVINTEL_LOADER;
